// frontend-angular/src/app/shared/ui/button/button.component.ts
import { NgClass } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

export type ButtonVariant = 'primary' | 'secondary' | 'destructive';
export type ButtonSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [NgClass],
  template: `
    <button
      class="vi-button"
      [attr.type]="type"
      [disabled]="disabled"
      [ngClass]="buttonClasses"
      (click)="pressed.emit($event)"
    >
      <ng-content />
    </button>
  `,
  styles: `
    .vi-button {
      border-radius: 1rem;
      border: 2px solid transparent;
      font-weight: 500;
      transition: all 150ms ease;
      cursor: pointer;
    }

    .vi-button:disabled {
      opacity: 0.45;
      cursor: not-allowed;
    }

    .vi-button.full {
      width: 100%;
    }

    .vi-button.variant-primary {
      background: var(--color-accent);
      color: var(--color-foreground);
      border-color: var(--color-accent);
      box-shadow: 0 0 20px rgba(91, 222, 234, 0.2);
    }

    .vi-button.variant-primary:hover:not(:disabled) {
      background: var(--color-accent-hover);
      border-color: var(--color-accent-hover);
    }

    .vi-button.variant-secondary {
      background: transparent;
      color: var(--color-accent);
      border-color: color-mix(in srgb, var(--color-accent) 55%, transparent);
    }

    .vi-button.variant-secondary:hover:not(:disabled) {
      background: color-mix(in srgb, var(--color-accent) 15%, transparent);
    }

    .vi-button.variant-destructive {
      background: var(--color-destructive);
      color: var(--color-foreground);
      border-color: var(--color-destructive);
    }

    .vi-button.variant-destructive:hover:not(:disabled) {
      background: var(--color-destructive-hover);
      border-color: var(--color-destructive-hover);
    }

    .vi-button.size-sm {
      padding: 0.5rem 1rem;
      font-size: 0.875rem;
    }

    .vi-button.size-md {
      padding: 0.75rem 1.25rem;
      font-size: 1rem;
    }

    .vi-button.size-lg {
      padding: 1rem 1.5rem;
      font-size: 1.125rem;
    }
  `
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'md';
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() disabled = false;
  @Input() fullWidth = false;
  @Output() pressed = new EventEmitter<MouseEvent>();

  get buttonClasses(): string[] {
    return [
      `variant-${this.variant}`,
      `size-${this.size}`,
      this.fullWidth ? 'full' : ''
    ];
  }
}

    <button
      class="vi-button"
      [attr.type]="type"
      [disabled]="disabled"
      [ngClass]="buttonClasses"
      (click)="pressed.emit($event)"
    >
      <ng-content />
    </button>

// frontend/src/components/Button.tsx
import { motion } from 'motion/react';
import { ReactNode } from 'react';

interface ButtonProps {
  children: ReactNode;
  variant?: 'primary' | 'secondary' | 'destructive';
  size?: 'sm' | 'md' | 'lg';
  disabled?: boolean;
  onClick?: () => void;
  className?: string;
  fullWidth?: boolean;
}

export function Button({ 
  children, 
  variant = 'primary', 
  size = 'md',
  disabled = false,
  onClick,
  className = '',
  fullWidth = false
}: ButtonProps) {
  const baseClass = "font-medium rounded-2xl transition-all disabled:opacity-40 disabled:cursor-not-allowed";
  
  const variantClass = {
    primary: "bg-accent text-background border-2 border-accent hover:bg-accent-hover hover:border-accent-hover shadow-[0_0_20px_rgba(91,222,234,0.2)] hover:shadow-[0_0_25px_rgba(91,222,234,0.3)] disabled:shadow-none",
    secondary: "bg-transparent text-accent border-2 border-accent/50 hover:bg-accent/10 hover:border-accent",
    destructive: "bg-destructive text-foreground border-2 border-destructive hover:bg-destructive-hover hover:border-destructive-hover shadow-[0_0_15px_rgba(200,93,93,0.2)]"
  }[variant];

  const sizeClass = {
    sm: "px-4 py-2 text-sm",
    md: "px-6 py-3 text-base",
    lg: "px-8 py-4 text-lg"
  }[size];

  const widthClass = fullWidth ? "w-full" : "";

  return (
    <motion.button
      whileTap={{ scale: disabled ? 1 : 0.97 }}
      className={`${baseClass} ${variantClass} ${sizeClass} ${widthClass} ${className}`}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </motion.button>
  );
}
