// frontend-angular/src/app/shared/ui/phase-indicator/phase-indicator.component.ts
import { Component, Input } from '@angular/core';

export type GamePhase = 'lobby' | 'reveal' | 'day' | 'vote' | 'execute' | 'night';

const PHASE_META: Record<GamePhase, { icon: string; label: string; color: string }> = {
  lobby: { icon: '👥', label: 'Lobby', color: 'var(--color-muted-foreground)' },
  reveal: { icon: '👁', label: 'Role Reveal', color: 'var(--color-accent)' },
  day: { icon: '☀', label: 'Day Discussion', color: 'var(--color-warning)' },
  vote: { icon: '🗳', label: 'Voting', color: 'var(--color-accent)' },
  execute: { icon: '☠', label: 'Execution', color: 'var(--color-destructive)' },
  night: { icon: '🌙', label: 'Night Phase', color: 'var(--color-accent)' }
};

@Component({
  selector: 'app-phase-indicator',
  standalone: true,
  template: `
    <div class="phase-pill">
      <span class="phase-icon" [style.color]="meta.color" aria-hidden="true">{{ meta.icon }}</span>
      <span class="phase-label">{{ meta.label }}</span>
    </div>
  `,
  styles: `
    .phase-pill {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      border-radius: 999px;
      border: 1px solid var(--color-border);
      background: color-mix(in srgb, var(--color-card) 80%, transparent);
      padding: 0.45rem 0.8rem;
    }

    .phase-icon {
      line-height: 1;
      font-size: 0.9rem;
    }

    .phase-label {
      text-transform: uppercase;
      letter-spacing: 0.08em;
      font-size: 0.72rem;
      font-weight: 600;
    }
  `
})
export class PhaseIndicatorComponent {
  @Input() phase: GamePhase = 'lobby';

  get meta(): { icon: string; label: string; color: string } {
    return PHASE_META[this.phase] ?? PHASE_META.lobby;
  }
}

    <div class="phase-pill">
      <span class="phase-icon" [style.color]="meta.color" aria-hidden="true">{{ meta.icon }}</span>
      <span class="phase-label">{{ meta.label }}</span>
    </div>

// frontend/src/components/PhaseIndicator.tsx
import { Moon, Sun, Vote, Skull, Users, Eye } from 'lucide-react';

type Phase = 'lobby' | 'reveal' | 'day' | 'vote' | 'execute' | 'night';

interface PhaseIndicatorProps {
  phase: Phase;
}

export function PhaseIndicator({ phase }: PhaseIndicatorProps) {
  const phases = {
    lobby: { icon: Users, label: 'Lobby', color: 'text-muted-foreground' },
    reveal: { icon: Eye, label: 'Role Reveal', color: 'text-accent' },
    day: { icon: Sun, label: 'Day Discussion', color: 'text-warning' },
    vote: { icon: Vote, label: 'Voting', color: 'text-accent' },
    execute: { icon: Skull, label: 'Execution', color: 'text-destructive' },
    night: { icon: Moon, label: 'Night Phase', color: 'text-accent' },
  };

  const current = phases[phase];
  const Icon = current.icon;

  return (
    <div className="flex items-center justify-center gap-2 px-4 py-2 bg-card border border-border rounded-full">
      <Icon className={`w-4 h-4 ${current.color}`} />
      <span className="text-sm font-medium uppercase tracking-wider" style={{ fontVariant: 'small-caps' }}>
        {current.label}
      </span>
    </div>
  );
}
