// frontend-angular/src/app/shared/ui/role-card/role-card.component.ts
import { Component, EventEmitter, Input, Output, signal } from '@angular/core';

export type Role = 'villager' | 'vampire' | 'hunter';

const ROLE_META: Record<Role, { name: string; instruction: string }> = {
  villager: {
    name: 'VILLAGER',
    instruction: 'Survive and find the vampire.'
  },
  vampire: {
    name: 'VAMPIRE',
    instruction: 'Eliminate villagers without being caught.'
  },
  hunter: {
    name: 'HUNTER',
    instruction: 'Inspect one player each night.'
  }
};

@Component({
  selector: 'app-role-card',
  standalone: true,
  template: `
    <button class="role-card" type="button" (click)="onCardClick()">
      @if (!isRevealed) {
        <div class="face">
          <p class="face-title">Tap to Reveal</p>
          <p class="face-subtitle">Private role card</p>
        </div>
      } @else {
        <div class="face revealed">
          <h3 class="role-name" [style.filter]="nameFilter">{{ roleMeta.name }}</h3>
          <p class="role-text" [style.filter]="instructionFilter">{{ roleMeta.instruction }}</p>

          @if (privacyMode) {
            <span
              class="hold-chip"
              (mousedown)="setUnblurred(true)"
              (mouseup)="setUnblurred(false)"
              (mouseleave)="setUnblurred(false)"
              (touchstart)="setUnblurred(true)"
              (touchend)="setUnblurred(false)"
            >
              {{ isUnblurred() ? 'Release to hide' : 'Hold to read' }}
            </span>
          }
        </div>
      }
    </button>
  `,
  styles: `
    .role-card {
      width: min(100%, 280px);
      aspect-ratio: 3 / 4;
      border: 2px solid color-mix(in srgb, var(--color-accent) 35%, transparent);
      border-radius: 1.1rem;
      background: color-mix(in srgb, var(--color-card) 85%, transparent);
      color: var(--color-foreground);
      cursor: pointer;
      box-shadow: inset 0 2px 8px rgba(0, 0, 0, 0.3), 0 8px 24px rgba(91, 222, 234, 0.12);
      padding: 1rem;
      text-align: center;
    }

    .face {
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      gap: 0.5rem;
    }

    .face-title {
      margin: 0;
      font-size: 1.2rem;
      font-weight: 700;
      color: var(--color-accent);
    }

    .face-subtitle {
      margin: 0;
      color: var(--color-muted-foreground);
      font-size: 0.85rem;
      text-transform: uppercase;
      letter-spacing: 0.08em;
    }

    .face.revealed {
      gap: 0.95rem;
      justify-content: center;
      padding: 0.5rem;
      position: relative;
    }

    .role-name {
      margin: 0;
      font-size: 1.45rem;
      letter-spacing: 0.08em;
      color: var(--color-accent);
      transition: filter 150ms ease;
    }

    .role-text {
      margin: 0;
      color: var(--color-muted-foreground);
      line-height: 1.45;
      transition: filter 150ms ease;
    }

    .hold-chip {
      position: absolute;
      bottom: 0.4rem;
      left: 50%;
      transform: translateX(-50%);
      border-radius: 999px;
      border: 1px solid color-mix(in srgb, var(--color-muted-foreground) 35%, transparent);
      background: color-mix(in srgb, var(--color-muted) 40%, transparent);
      color: var(--color-muted-foreground);
      font-size: 0.68rem;
      padding: 0.3rem 0.55rem;
      user-select: none;
    }
  `
})
export class RoleCardComponent {
  @Input() role: Role = 'villager';
  @Input() isRevealed = false;
  @Input() privacyMode = true;
  @Output() reveal = new EventEmitter<void>();

  readonly isUnblurred = signal(false);

  get roleMeta(): { name: string; instruction: string } {
    return ROLE_META[this.role];
  }

  get nameFilter(): string {
    return this.privacyMode && !this.isUnblurred() ? 'blur(8px)' : 'none';
  }

  get instructionFilter(): string {
    return this.privacyMode && !this.isUnblurred() ? 'blur(6px)' : 'none';
  }

  onCardClick(): void {
    if (!this.isRevealed) {
      this.reveal.emit();
    }
  }

  setUnblurred(isUnblurred: boolean): void {
    this.isUnblurred.set(isUnblurred);
  }
}

    <button class="role-card" type="button" (click)="onCardClick()">
      @if (!isRevealed) {
        <div class="face">
          <p class="face-title">Tap to Reveal</p>
          <p class="face-subtitle">Private role card</p>
        </div>
      } @else {
        <div class="face revealed">
          <h3 class="role-name" [style.filter]="nameFilter">{{ roleMeta.name }}</h3>
          <p class="role-text" [style.filter]="instructionFilter">{{ roleMeta.instruction }}</p>

          @if (privacyMode) {
            <span
              class="hold-chip"
              (mousedown)="setUnblurred(true)"
              (mouseup)="setUnblurred(false)"
              (mouseleave)="setUnblurred(false)"
              (touchstart)="setUnblurred(true)"
              (touchend)="setUnblurred(false)"
            >
              {{ isUnblurred() ? 'Release to hide' : 'Hold to read' }}
            </span>
          }
        </div>
      }
    </button>

// frontend/src/components/RoleCard.tsx
import { motion } from 'motion/react';
import { useState } from 'react';
import { Eye, EyeOff } from 'lucide-react';

type Role = 'villager' | 'vampire' | 'hunter';

interface RoleCardProps {
  role: Role;
  isRevealed: boolean;
  onReveal?: () => void;
  privacyMode?: boolean;
}

const roleData = {
  villager: {
    name: 'VILLAGER',
    instruction: 'Survive and find the vampire'
  },
  vampire: {
    name: 'VAMPIRE',
    instruction: 'Kill villagers without being caught'
  },
  hunter: {
    name: 'HUNTER',
    instruction: 'Inspect one player each night'
  }
};

export function RoleCard({ role, isRevealed, onReveal, privacyMode = true }: RoleCardProps) {
  const [isUnblurred, setIsUnblurred] = useState(false);
  const data = roleData[role];

  return (
    <motion.div
      className="relative w-full max-w-[280px] aspect-[3/4] cursor-pointer"
      onClick={!isRevealed ? onReveal : undefined}
      style={{ perspective: 1000 }}
    >
      <motion.div
        className="relative w-full h-full"
        initial={false}
        animate={{ rotateY: isRevealed ? 180 : 0 }}
        transition={{ duration: 0.6, ease: 'easeInOut' }}
        style={{ transformStyle: 'preserve-3d' }}
      >
        {/* FRONT SIDE - Identical for all */}
        <div
          className="absolute inset-0 rounded-[18px] bg-card border-2 border-accent/30 shadow-[inset_0_2px_8px_rgba(0,0,0,0.3),0_8px_32px_rgba(91,222,234,0.15)] flex items-center justify-center"
          style={{ backfaceVisibility: 'hidden' }}
        >
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-accent/10 border border-accent/30 flex items-center justify-center">
              <Eye className="w-8 h-8 text-accent" />
            </div>
            <p className="text-sm text-muted-foreground uppercase tracking-wider" style={{ fontVariant: 'small-caps' }}>
              Tap to Reveal
            </p>
          </div>
        </div>

        {/* BACK SIDE - IDENTICAL for all roles (anti-peeking) */}
        <div
          className="absolute inset-0 rounded-[18px] bg-card border-2 border-accent/30 shadow-[inset_0_2px_8px_rgba(0,0,0,0.3),0_8px_32px_rgba(91,222,234,0.15)] flex flex-col items-center justify-center p-8"
          style={{ 
            backfaceVisibility: 'hidden',
            transform: 'rotateY(180deg)'
          }}
        >
          {/* Icon area - same for all */}
          <div className="w-16 h-16 mb-6 rounded-full bg-accent/10 border border-accent/30 flex items-center justify-center">
            <Eye className="w-8 h-8 text-accent" />
          </div>

          {/* Role name - with identical blur when privacy mode is on */}
          <div className="relative mb-4">
            <h2 
              className="text-2xl font-bold uppercase tracking-wider text-center text-accent"
              style={{ 
                filter: (privacyMode && !isUnblurred) ? 'blur(8px)' : 'none',
                transition: 'filter 0.2s'
              }}
            >
              {data.name}
            </h2>
          </div>

          {/* Instruction - with identical blur */}
          <p 
            className="text-sm text-center text-muted-foreground leading-relaxed"
            style={{ 
              filter: (privacyMode && !isUnblurred) ? 'blur(6px)' : 'none',
              transition: 'filter 0.2s'
            }}
          >
            {data.instruction}
          </p>

          {/* Privacy mode indicator - identical for all */}
          {privacyMode && (
            <motion.div
              className="absolute bottom-4 left-1/2 -translate-x-1/2"
              onMouseDown={() => setIsUnblurred(true)}
              onMouseUp={() => setIsUnblurred(false)}
              onMouseLeave={() => setIsUnblurred(false)}
              onTouchStart={() => setIsUnblurred(true)}
              onTouchEnd={() => setIsUnblurred(false)}
            >
              <div className="flex items-center gap-2 px-3 py-1.5 bg-muted/50 rounded-full text-xs text-muted-foreground">
                {isUnblurred ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
                <span>Hold to read</span>
              </div>
            </motion.div>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}
