// frontend/src/components/Timer.tsx
import { Clock } from 'lucide-react';
import { motion } from 'motion/react';

interface TimerProps {
  seconds: number;
  totalSeconds: number;
  label?: string;
}

export function Timer({ seconds, totalSeconds, label = "Time remaining" }: TimerProps) {
  const progress = (seconds / totalSeconds) * 100;
  const minutes = Math.floor(seconds / 60);
  const secs = seconds % 60;
  const isLow = seconds <= 10;

  return (
    <div className="bg-card border border-border rounded-2xl p-4">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Clock className="w-4 h-4 text-accent" />
          <span className="text-sm text-muted-foreground">{label}</span>
        </div>
        <span className={`text-2xl font-bold tabular-nums ${isLow ? 'text-error' : 'text-accent'}`}>
          {minutes}:{secs.toString().padStart(2, '0')}
        </span>
      </div>
      
      <div className="h-2 bg-muted rounded-full overflow-hidden">
        <motion.div
          className={`h-full ${isLow ? 'bg-error' : 'bg-accent'}`}
          initial={{ width: '100%' }}
          animate={{ width: `${progress}%` }}
          transition={{ duration: 1, ease: 'linear' }}
        />
      </div>
    </div>
  );
}

// frontend-angular/src/app/shared/ui/timer/timer.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-timer',
  standalone: true,
  template: `
    <section class="timer-card">
      <div class="timer-row">
        <span class="timer-label">{{ label }}</span>
        <span class="timer-value" [class.low]="isLow">{{ formattedTime }}</span>
      </div>

      <div class="track">
        <div class="fill" [class.low]="isLow" [style.width.%]="progress"></div>
      </div>
    </section>
  `,
  styles: `
    .timer-card {
      border: 1px solid var(--color-border);
      border-radius: 1rem;
      background: color-mix(in srgb, var(--color-card) 80%, transparent);
      padding: 0.9rem;
    }

    .timer-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 0.55rem;
    }

    .timer-label {
      color: var(--color-muted-foreground);
      font-size: 0.82rem;
    }

    .timer-value {
      color: var(--color-accent);
      font-size: 1.3rem;
      line-height: 1;
      font-variant-numeric: tabular-nums;
      font-weight: 700;
    }

    .timer-value.low {
      color: var(--color-error);
    }

    .track {
      height: 0.45rem;
      border-radius: 999px;
      background: var(--color-muted);
      overflow: hidden;
    }

    .fill {
      height: 100%;
      background: var(--color-accent);
      transition: width 350ms linear;
    }

    .fill.low {
      background: var(--color-error);
    }
  `
})
export class TimerComponent {
  @Input() seconds = 0;
  @Input() totalSeconds = 1;
  @Input() label = 'Time remaining';

  get progress(): number {
    if (this.totalSeconds <= 0) {
      return 0;
    }
    const percent = (this.seconds / this.totalSeconds) * 100;
    return Math.min(100, Math.max(0, percent));
  }

  get isLow(): boolean {
    return this.seconds <= 10;
  }

  get formattedTime(): string {
    const minutes = Math.floor(this.seconds / 60);
    const remaining = Math.max(0, this.seconds % 60);
    return `${minutes}:${String(remaining).padStart(2, '0')}`;
  }
}

    <section class="timer-card">
      <div class="timer-row">
        <span class="timer-label">{{ label }}</span>
        <span class="timer-value" [class.low]="isLow">{{ formattedTime }}</span>
      </div>

      <div class="track">
        <div class="fill" [class.low]="isLow" [style.width.%]="progress"></div>
      </div>
    </section>
