// frontend/src/components/AppHeader.tsx
import { Copy, Wifi, WifiOff, LogOut } from 'lucide-react';
import { toast } from 'sonner';

interface AppHeaderProps {
  roomCode?: string;
  isConnected?: boolean;
  onLeave?: () => void;
  showLeave?: boolean;
}

export function AppHeader({ roomCode, isConnected = true, onLeave, showLeave = true }: AppHeaderProps) {
  const handleCopyCode = () => {
    if (roomCode) {
      navigator.clipboard.writeText(roomCode);
      toast.success('Room code copied!');
    }
  };

  return (
    <header className="flex items-center justify-between px-5 py-4 border-b border-border/50">
      <div className="flex items-center gap-3">
        {roomCode && (
          <button
            onClick={handleCopyCode}
            className="flex items-center gap-2 px-3 py-1.5 bg-card border border-border rounded-full text-sm font-medium hover:bg-card-hover transition-colors"
          >
            <span className="tracking-widest">{roomCode}</span>
            <Copy className="w-3.5 h-3.5 text-accent" />
          </button>
        )}
        
        <div className="flex items-center gap-1.5 px-2.5 py-1.5 bg-card/50 rounded-full">
          {isConnected ? (
            <Wifi className="w-3.5 h-3.5 text-accent" />
          ) : (
            <WifiOff className="w-3.5 h-3.5 text-error" />
          )}
          <span className="text-xs text-muted-foreground">
            {isConnected ? 'Connected' : 'Reconnecting...'}
          </span>
        </div>
      </div>

      {showLeave && onLeave && (
        <button
          onClick={onLeave}
          className="p-2 hover:bg-muted rounded-lg transition-colors"
          aria-label="Leave room"
        >
          <LogOut className="w-5 h-5 text-muted-foreground" />
        </button>
      )}
    </header>
  );
}

// frontend-angular/src/app/shared/ui/app-header/app-header.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-app-header',
  standalone: true,
  template: `
    <header class="vi-header">
      <div class="vi-header__left">
        @if (roomCode) {
          <button class="chip chip-code" type="button" (click)="copyRoomCode()">
            <span class="room-code">{{ roomCode }}</span>
            <span aria-hidden="true">⎘</span>
          </button>
        }

        <div class="chip chip-state">
          <span class="state-dot" [class.connected]="isConnected" [class.disconnected]="!isConnected"></span>
          <span>{{ isConnected ? 'Connected' : 'Reconnecting...' }}</span>
        </div>
      </div>

      @if (showLeave) {
        <button class="leave-button" type="button" aria-label="Leave room" (click)="leave.emit()">
          Exit
        </button>
      }
    </header>
  `,
  styles: `
    .vi-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 0.75rem;
      padding: 1rem 1.25rem;
      border-bottom: 1px solid color-mix(in srgb, var(--color-border) 55%, transparent);
    }

    .vi-header__left {
      display: flex;
      align-items: center;
      gap: 0.6rem;
      min-width: 0;
    }

    .chip {
      display: inline-flex;
      align-items: center;
      gap: 0.35rem;
      border-radius: 999px;
      border: 1px solid var(--color-border);
      background: color-mix(in srgb, var(--color-card) 85%, transparent);
      color: var(--color-foreground);
      font-size: 0.75rem;
      padding: 0.4rem 0.65rem;
      min-height: 2rem;
    }

    .chip-code {
      cursor: pointer;
    }

    .room-code {
      letter-spacing: 0.18em;
      font-weight: 600;
    }

    .chip-state {
      color: var(--color-muted-foreground);
    }

    .state-dot {
      width: 0.5rem;
      height: 0.5rem;
      border-radius: 50%;
      display: inline-block;
    }

    .state-dot.connected {
      background: var(--color-success);
    }

    .state-dot.disconnected {
      background: var(--color-error);
    }

    .leave-button {
      border: 1px solid var(--color-border);
      border-radius: 0.6rem;
      background: transparent;
      color: var(--color-muted-foreground);
      font-size: 0.75rem;
      padding: 0.45rem 0.7rem;
      cursor: pointer;
    }

    .leave-button:hover {
      color: var(--color-foreground);
      background: color-mix(in srgb, var(--color-muted) 45%, transparent);
    }
  `
})
export class AppHeaderComponent {
  @Input() roomCode?: string;
  @Input() isConnected = true;
  @Input() showLeave = true;

  @Output() leave = new EventEmitter<void>();
  @Output() copied = new EventEmitter<string>();

  async copyRoomCode(): Promise<void> {
    if (!this.roomCode) {
      return;
    }

    try {
      await navigator.clipboard.writeText(this.roomCode);
    } catch {
      // no-op fallback for unsupported clipboard environments
    }

    this.copied.emit(this.roomCode);
  }
}

    <header class="vi-header">
      <div class="vi-header__left">
        @if (roomCode) {
          <button class="chip chip-code" type="button" (click)="copyRoomCode()">
            <span class="room-code">{{ roomCode }}</span>
            <span aria-hidden="true">⎘</span>
          </button>
        }

        <div class="chip chip-state">
          <span class="state-dot" [class.connected]="isConnected" [class.disconnected]="!isConnected"></span>
          <span>{{ isConnected ? 'Connected' : 'Reconnecting...' }}</span>
        </div>
      </div>

      @if (showLeave) {
        <button class="leave-button" type="button" aria-label="Leave room" (click)="leave.emit()">
          Exit
        </button>
      }
    </header>
